name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  # Changelog
  $CHANGES

  See details of [all code changes](https://github.com/sdf-labs/sdf-action/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION) since previous release

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "infrastructure"
      - "automation"
      - "documentation"
      - "dependencies"
      - "maintenance"
      - "revert"
  - title: "🏎 Performance"
    label: "performance"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "enhancement"
      - "fix"
  patch:
    labels:
      - "documentation"
      - "maintenance"
  default: patch
