# action.yml
name: "dbt action"
description: "Run sdf cli commands"
inputs:
  command:
    description: "The sdf command to run"
    default: "sdf compile"
    required: true
  workspace_dir:
    description: "The directory of the workspace"
    default: "."
    required: true
  access_key:
    description: "The access key"
    required: true
  secret_key:
    description: "The secret key"
    required: true

  # required if snowflake table provider is used
  snowflake_account_id:
    description: "The snowflake account id"
    required: false
  snowflake_username:
    description: "The snowflake username"
    required: false
  snowflake_password:
    description: "The snowflake password"
    required: false
  snowflake_role:
    description: "The snowflake role"
    required: false
  snowflake_warehouse:
    description: "The snowflake warehouse"
    required: false

outputs:
  result:
    description: "The log of the command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
  env:
    WORKSPACE_DIR: ${{ inputs.workspace_dir }}
    ACCESS_KEY: ${{ inputs.access_key }}
    SECRET_KEY: ${{ inputs.secret_key }}

    SNOWFLAKE_ACCOUNT_ID: ${{ inputs.snowflake_account_id }}
    SNOWFLAKE_USERNAME: ${{ inputs.snowflake_username }}
    SNOWFLAKE_PASSWORD: ${{ inputs.snowflake_password }}
    SNOWFLAKE_ROLE: ${{ inputs.snowflake_role }}
    SNOWFLAKE_WAREHOUSE: ${{ inputs.snowflake_warehouse }}
