# action.yml
name: "sdf action"
description: "Run sdf cli commands"
inputs:
  sdf_version:
    description: "The version of the sdf cli"
    default: "latest"
    required: false
  command:
    description: "The sdf command to run"
    default: "sdf compile"
    required: false
  workspace_dir:
    description: "The directory of the workspace"
    default: "."
    required: false
  access_key:
    description: "The access key"
    required: false
  secret_key:
    description: "The secret key"
    required: false
  is_dbt:
    description: "Whether the workspace is dbt based or not"
    required: false
    default: ""
  dbt_profiles_dir:
    description: "Used to pass in a custom path to a dbt profiles.yml file. If not set, it will use dbt's behavior of looking in the same dir as the dbt_project.yml file, then if not there look in the .dbt dir in the user's home directory."
    required: false
    default: ""

  # required if snowflake table provider is used
  snowflake_account_id:
    description: "The snowflake account id"
    required: false
  snowflake_username:
    description: "The snowflake username"
    required: false
  snowflake_password:
    description: "The snowflake password"
    required: false
  snowflake_private_key_path:
    description: "The path to the private key file"
    required: false
  snowflake_private_key_pem:
    description: "The private key pem"
    required: false
  snowflake_private_key_passphrase:
    description: "The private key passphrase"
    required: false
  snowflake_role:
    description: "The snowflake role"
    required: false
  snowflake_warehouse:
    description: "The snowflake warehouse"
    required: false

  # required if redshift table provider is used
  aws_region:
    description: "The aws region"
    required: false
  aws_access_key_id:
    description: "The aws access key id"
    required: false
  aws_secret_access_key:
    description: "The aws secret access key"
    required: false

  # required if bigquery table provider is used
  bigquery_project_id:
    description: "The bigquery project id"
    required: false
  bigquery_client_email:
    description: "The bigquery client email"
    required: false
  bigquery_private_key:
    description: "The private key pem"
    required: false
  bigquery_credentials_json_path:
    description: "The path to the bigquery credentials json file"
    required: false

outputs:
  result:
    description: "The result (pass or failed)"
  log:
    description: "The log of the command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
    - ${{ inputs.is_dbt }}
    - ${{ inputs.sdf_version }}
    - ${{ inputs.dbt_profiles_dir }}
  env:
    WORKSPACE_DIR: ${{ inputs.workspace_dir }}
    ACCESS_KEY: ${{ inputs.access_key }}
    SECRET_KEY: ${{ inputs.secret_key }}

    SNOWFLAKE_ACCOUNT_ID: ${{ inputs.snowflake_account_id }}
    SNOWFLAKE_USERNAME: ${{ inputs.snowflake_username }}
    SNOWFLAKE_PASSWORD: ${{ inputs.snowflake_password }}
    SNOWFLAKE_ROLE: ${{ inputs.snowflake_role }}
    SNOWFLAKE_WAREHOUSE: ${{ inputs.snowflake_warehouse }}
    SNOWFLAKE_PRIVATE_KEY_PATH: ${{ inputs.snowflake_private_key_path }}
    SNOWFLAKE_PRIVATE_KEY_PEM: ${{ inputs.snowflake_private_key_pem }}
    SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ inputs.snowflake_private_key_passphrase }}

    AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
    AWS_DEFAULT_REGION: ${{ inputs.aws_region }}

    BIGQUERY_PROJECT_ID: ${{ inputs.bigquery_project_id }}
    BIGQUERY_CLIENT_EMAIL: ${{ inputs.bigquery_client_email }}
    BIGQUERY_PRIVATE_KEY: ${{ inputs.bigquery_private_key }}
    BIGQUERY_CREDENTIALS_JSON_PATH: ${{ inputs.bigquery_credentials_json_path }}
