# action.yml
name: "dbt action"
description: "Run sdf cli commands"
inputs:
  command:
    description: "The sdf command to run"
    default: "sdf compile"
    required: true
  workspace_dir:
    description: "The directory of the workspace"
    default: "."
    required: true
  access_key:
    description: "The access key"
    required: true
  secret_key:
    description: "The secret key"
    required: true
outputs:
  result:
    description: "The log of the command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
  env:
    WORKSPACE_DIR: ${{ inputs.workspace_dir }}
    ACCESS_KEY: ${{ inputs.access_key }}
    SECRET_KEY: ${{ inputs.secret_key }}
