# action.yml
name: "sdf action"
description: "Run sdf cli commands"
inputs:
  sdf_version:
    description: "The version of the sdf cli"
    default: "0.2.10"
    required: false
  command:
    description: "The sdf command to run"
    default: "sdf compile"
    required: false
  workspace_dir:
    description: "The directory of the workspace"
    default: "."
    required: false
  access_key:
    description: "The access key"
    required: false
  secret_key:
    description: "The secret key"
    required: false
  is_dbt:
    description: "Whether the workspace is dbt based or not"
    required: false
    default: ""
  dbt_target:
    description: "The dbt target"
    required: false
    default: "dev"

  # required if snowflake table provider is used
  snowflake_account_id:
    description: "The snowflake account id"
    required: false
  snowflake_username:
    description: "The snowflake username"
    required: false
  snowflake_password:
    description: "The snowflake password"
    required: false
  snowflake_role:
    description: "The snowflake role"
    required: false
  snowflake_warehouse:
    description: "The snowflake warehouse"
    required: false

  # required if redshift table provider is used
  aws_region:
    description: "The aws region"
    required: false
  aws_access_key_id:
    description: "The aws access key id"
    required: false
  aws_secret_access_key:
    description: "The aws secret access key"
    required: false

outputs:
  result:
    description: "The result (pass or failed)"
  log:
    description: "The log of the command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
    - ${{ inputs.is_dbt }}
    - ${{ inputs.sdf_version }}
    - ${{ inputs.snowflake_provider }}
  env:
    WORKSPACE_DIR: ${{ inputs.workspace_dir }}
    ACCESS_KEY: ${{ inputs.access_key }}
    SECRET_KEY: ${{ inputs.secret_key }}

    SNOWFLAKE_ACCOUNT_ID: ${{ inputs.snowflake_account_id }}
    SNOWFLAKE_USERNAME: ${{ inputs.snowflake_username }}
    SNOWFLAKE_PASSWORD: ${{ inputs.snowflake_password }}
    SNOWFLAKE_ROLE: ${{ inputs.snowflake_role }}
    SNOWFLAKE_WAREHOUSE: ${{ inputs.snowflake_warehouse }}
    DBT_TARGET: ${{ inputs.dbt_target }}

    AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
    AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
