# Path: crates/sdf-cli/workspaces/dbt/snowflake/dbt_hol/models/sources.yml
version: 2

sources:
  - name: users
    database: dbt_hol_dev
    schema: public
    tables:
      - name: users
  - name: census_sources
    database: census
    schema: public
    quoting: 
      identifier: true
      column: true
    tables:
      - name: 2019_RENT_PERCENTAGE_HOUSEHOLD_INCOME
        columns:
          - name: "CENSUS_BLOCK_GROUP"
            description: 'Description of the column'
            tests:
              - not_null
          - name: "Total: Renter-occupied housing units"
            description: 'Description of the column'
            tests:
              - not_null
          - name: "50.0 percent or more: Renter-occupied housing units"
            description: 'Description of the column'
            tests:
              - not_null
          - name: "Not computed: Renter-occupied housing units"
            description: 'Description of the column'
            tests:
              - not_null
          - name: "Less than 10.0 percent: Renter-occupied housing units"
            description: 'Description of the column'
            tests:
              - not_null
          - name: "10.0 to 14.9 percent: Renter-occupied housing units"
            description: 'Description of the column'
            tests:
              - not_null
          - name: "15.0 to 19.9 percent: Renter-occupied housing units"
            description: 'Description of the column'
            tests:
              - not_null
          - name: "20.0 to 24.9 percent: Renter-occupied housing units"
            description: 'Description of the column'
            tests:
              - not_null
          - name: "25.0 to 29.9 percent: Renter-occupied housing units"
            description: 'Description of the column'
            tests:
              - not_null
          - name: "30.0 to 34.9 percent: Renter-occupied housing units"
            description: 'Description of the column'
            tests:
              - not_null
          - name: "35.0 to 39.9 percent: Renter-occupied housing units"
            description: 'Description of the column'
            tests:
              - not_null
          - name: "40.0 to 49.9 percent: Renter-occupied housing units"
            description: 'Description of the column'
            tests:
              - not_null

      - name: 2020_CBG_B16
        columns:
          - name: CENSUS_BLOCK_GROUP
            description: Description of the column
            tests:
              - not_null
              - unique
          - name: B16004e1
            description: Description of the column
            tests:
              - not_null
          - name: B16004m1
            description: Description of the column
            tests:
              - not_null
          - name: B16004e2
            description: Description of the column
            tests:
              - not_null
          - name: B16004m2
            description: Description of the column
            tests:
              - not_null
          - name: B16004e10
            description: Description of the column
            quote: true
            tests:
              - not_null
          # Continue this pattern for all columns...
          - name: B16004e67
            description: Description of the column
            tests:
              - not_null
          - name: B16004m67
            description: Description of the column
            tests:
              - not_null