name: 'snowflake_finances'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'my_first_dbt_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["yo"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# on-run-start: ["{{ create_logs_table('dbt_logs') }}"]
# on-run-end: ["{{ insert_log_records('dbt_logs') }}"]

models:
  snowflake_finances:
    staging:
      +schema: staging
      crm:
        +schema: staging
      furniture_mart:
        +schema: staging
    intermediate:
      +schema: staging
      finance:
      operations:
    marts:
      finance:
        +schema: finance
      operations:
        +schema: operations

seeds:

snapshots:

dispatch:
  - macro_namespace: dbt
    search_order:
      - my_first_dbt_project
      - dbt_snowflake_monitoring
      - dbt

query-comment:
  comment: '{{ dbt_snowflake_monitoring.get_query_comment(node) }}'
  append: true # Snowflake removes prefixed comments.
