name: Base sdf-action Docker Image (DBT based)

on:
  pull_request:
    paths:
      - 'Dockerfile.base'
  workflow_dispatch:
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
  
      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: |
          docker buildx build \
            --file Dockerfile.base \
            --platform linux/amd64,linux/arm64 .

      - name: Release Docker image
        if: github.event_name == 'workflow_dispatch'
        run: |
          docker buildx build \
            --file Dockerfile.base \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag ghcr.io/${{ github.repository }}-dbt-base:latest \
            --tag ghcr.io/${{ github.repository }}-dbt-base:${{ github.run_number }} .