name: Base Docker Image CI

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.base'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile.base'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
      
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --file Dockerfile.base \
            --platform linux/amd64,linux/arm64 \
            --push \
            --tag ghcr.io/${{ github.repository }}:${{ github.sha }} 