name: Test sdf-action

on:
  push:
    branches:
      - harry/test_public_action

jobs:
  dbt_init_challenge_v1:
    runs-on: ubuntu-latest
    name: Snowflake + dbt workspace - run dbt commands using dbt-action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        
      - name: Run DBT commands
        uses: mwhitaker/dbt-action@master
        env: 
          DBT_TARGET: dev
          SNOWFLAKE_ACCOUNT_ID: ${{ secrets.SNOWFLAKE_ACCOUNT_ID }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        with:
          dbt_command: "dbt compile"
          dbt_project_folder: "workspace/dbt_init_challenge"

      - name: Run sdf compile
        uses: sdf-labs/sdf-action@v0.0.1 # Uses an action in the root directory
        id: sdf
        env:
          CATALOG: dbt_hol_dev
          SCHEMA: public
        with:
          sdf_version: '0.1.183'
          command: 'sdf compile'
          workspace_dir: 'workspace/dbt_init_challenge'
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}

          is_dbt: 'true'
          snowflake_account_id: ${{ secrets.SNOWFLAKE_ACCOUNT_ID }}
          snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}
          snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
          snowflake_role: 'dbt_test_role'
          snowflake_warehouse: 'dbt_dev_wh'

      # Use the output from the `sdf` step
      - name: Display the sdf output
        run: |
          echo "### SDF Run Logs 🪵" >> $GITHUB_STEP_SUMMARY
          echo '```' >>$GITHUB_STEP_SUMMARY
          echo "${{ steps.sdf.outputs.log }}" >>$GITHUB_STEP_SUMMARY
          echo '```' >>$GITHUB_STEP_SUMMARY

  # dbt_init_challenge_v2: rus dbt commands in a container job
  dbt_init_challenge_v2:
    container:
      image: ghcr.io/dbt-labs/dbt-snowflake:1.5.latest
      volumes:
        - ${{ github.workspace }}:/repo
    
    runs-on: ubuntu-latest
    name: Snowflake + dbt workspace - run dbt commands in a container job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run DBT commands
        env:
          DBT_TARGET: dev
          SNOWFLAKE_ACCOUNT_ID: ${{ secrets.SNOWFLAKE_ACCOUNT_ID }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          cd /repo/workspace/dbt_init_challenge
          dbt deps
          dbt compile
      - name: Run sdf push
        uses: sdf-labs/sdf-action@v0.0.1 # Uses an action in the root directory
        id: sdf
        env:
          CATALOG: dbt_hol_dev
          SCHEMA: public
        with:
          sdf_version: '0.2.16'
          command: 'sdf push'
          # relative path to ${{ github.workspace }} which is automatically mounted by GitHub Actions
          workspace_dir: workspace/dbt_init_challenge
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}

          is_dbt: 'true'
          snowflake_account_id: ${{ secrets.SNOWFLAKE_ACCOUNT_ID }}
          snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}
          snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
          snowflake_role: 'dbt_test_role'
          snowflake_warehouse: 'dbt_dev_wh'
  
      # Use the output from the `sdf` step
      - name: Display the sdf output
        run: |
          echo "### SDF Run Logs 🪵" >> $GITHUB_STEP_SUMMARY
          echo '```' >>$GITHUB_STEP_SUMMARY
          echo "${{ steps.sdf.outputs.log }}" >>$GITHUB_STEP_SUMMARY
          echo '```' >>$GITHUB_STEP_SUMMARY

