on:
  push:
    branches:
      - 'main'

jobs:
  dbt_init_challenge_job:
    runs-on: ubuntu-latest
    name: Run sdf compile
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: sdf push step
        uses: ./ # Uses an action in the root directory
        id: sdf
        with:
          command: 'sdf push'
          workspace_dir: 'workspace/dbt_init_challenge'
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}

          snowflake_account_id: ${{ secrets.SNOWFLAKE_ACCOUNT_ID }}
          snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}
          snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
          snowflake_role: ${{ secrets.SNOWFLAKE_ROLE }}
          snowflake_warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}

          
      # Use the output from the `sdf` step
      - name: Get the sdf output
        run: echo "The result was ${{ steps.sdf.outputs.result }}"
