on:
  push:
    branches:
      - 'main'

jobs:
  sdf_job:
    runs-on: ubuntu-latest
    name: Run sdf compile
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: sdf compile step
        uses: ./ # Uses an action in the root directory
        id: sdf
        with:
          command: 'sdf compile'
          workspace_dir: 'workspace/lineage'
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}
          
      # Use the output from the `sdf` step
      - name: Get the sdf output
        run: echo "The result was ${{ steps.sdf.outputs.result }}"
